/* tslint:disable */
require("./FilePicker.module.css");
var styles = {
    filePicker: 'filePicker_d57d39bc',
    tabsContainer: 'tabsContainer_d57d39bc',
    tabContainer: 'tabContainer_d57d39bc',
    nav: 'nav_d57d39bc',
    tabHeaderContainer: 'tabHeaderContainer_d57d39bc',
    breadcrumbNav: 'breadcrumbNav_d57d39bc',
    breadcrumbNavItem: 'breadcrumbNavItem_d57d39bc',
    tab: 'tab_d57d39bc',
    tabOffset: 'tabOffset_d57d39bc',
    tabFiles: 'tabFiles_d57d39bc',
    scrollablePaneWrapper: 'scrollablePaneWrapper_d57d39bc',
    actionButtonsContainer: 'actionButtonsContainer_d57d39bc',
    actionButtons: 'actionButtons_d57d39bc',
    actionButton: 'actionButton_d57d39bc',
    tabHeader: 'tabHeader_d57d39bc',
    selectedTab: 'selectedTab_d57d39bc',
    header: 'header_d57d39bc',
    xlg: 'xlg_d57d39bc',
    xxlg: 'xxlg_d57d39bc',
    xxxlg: 'xxxlg_d57d39bc',
    xxxxlg: 'xxxxlg_d57d39bc',
    itemPickerTopBar: 'itemPickerTopBar_d57d39bc',
    commandBarNoChevron: 'commandBarNoChevron_d57d39bc',
    fileItem: 'fileItem_d57d39bc',
    folderItem: 'folderItem_d57d39bc',
    fileTypeIcon: 'fileTypeIcon_d57d39bc',
    fileTypeIconIcon: 'fileTypeIconIcon_d57d39bc',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_d57d39bc',
    iconColumnHeader: 'iconColumnHeader_d57d39bc',
    fileRow: 'fileRow_d57d39bc',
    folderRow: 'folderRow_d57d39bc',
    emptyFolder: 'emptyFolder_d57d39bc',
    emptyFolderImage: 'emptyFolderImage_d57d39bc',
    emptyFolderImageTag: 'emptyFolderImageTag_d57d39bc',
    emptyFolderTitle: 'emptyFolderTitle_d57d39bc',
    emptyFolderSubText: 'emptyFolderSubText_d57d39bc',
    emptyFolderMobile: 'emptyFolderMobile_d57d39bc',
    emptyFolderPc: 'emptyFolderPc_d57d39bc',
    emptyFolderIcon: 'emptyFolderIcon_d57d39bc'
};
export default styles;
/* tslint:enable */ 
//# sourceMappingURL=FilePicker.module.scss.js.map