/* tslint:disable */
require("./LinkFilePickerTab.module.css");
var styles = {
    filePicker: 'filePicker_9ea9ac71',
    tabsContainer: 'tabsContainer_9ea9ac71',
    tabContainer: 'tabContainer_9ea9ac71',
    nav: 'nav_9ea9ac71',
    tabHeaderContainer: 'tabHeaderContainer_9ea9ac71',
    breadcrumbNav: 'breadcrumbNav_9ea9ac71',
    breadcrumbNavItem: 'breadcrumbNavItem_9ea9ac71',
    tab: 'tab_9ea9ac71',
    tabOffset: 'tabOffset_9ea9ac71',
    tabFiles: 'tabFiles_9ea9ac71',
    scrollablePaneWrapper: 'scrollablePaneWrapper_9ea9ac71',
    actionButtonsContainer: 'actionButtonsContainer_9ea9ac71',
    actionButtons: 'actionButtons_9ea9ac71',
    actionButton: 'actionButton_9ea9ac71',
    tabHeader: 'tabHeader_9ea9ac71',
    selectedTab: 'selectedTab_9ea9ac71',
    header: 'header_9ea9ac71',
    xlg: 'xlg_9ea9ac71',
    xxlg: 'xxlg_9ea9ac71',
    xxxlg: 'xxxlg_9ea9ac71',
    xxxxlg: 'xxxxlg_9ea9ac71',
    itemPickerTopBar: 'itemPickerTopBar_9ea9ac71',
    commandBarNoChevron: 'commandBarNoChevron_9ea9ac71',
    fileItem: 'fileItem_9ea9ac71',
    folderItem: 'folderItem_9ea9ac71',
    fileTypeIcon: 'fileTypeIcon_9ea9ac71',
    fileTypeIconIcon: 'fileTypeIconIcon_9ea9ac71',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_9ea9ac71',
    iconColumnHeader: 'iconColumnHeader_9ea9ac71',
    fileRow: 'fileRow_9ea9ac71',
    folderRow: 'folderRow_9ea9ac71',
    emptyFolder: 'emptyFolder_9ea9ac71',
    emptyFolderImage: 'emptyFolderImage_9ea9ac71',
    emptyFolderImageTag: 'emptyFolderImageTag_9ea9ac71',
    emptyFolderTitle: 'emptyFolderTitle_9ea9ac71',
    emptyFolderSubText: 'emptyFolderSubText_9ea9ac71',
    emptyFolderMobile: 'emptyFolderMobile_9ea9ac71',
    emptyFolderPc: 'emptyFolderPc_9ea9ac71',
    emptyFolderIcon: 'emptyFolderIcon_9ea9ac71',
    linkTextField: 'linkTextField_9ea9ac71',
    localTabSinglePreview: 'localTabSinglePreview_9ea9ac71',
    localTabSinglePreviewImage: 'localTabSinglePreviewImage_9ea9ac71'
};
export default styles;
/* tslint:enable */ 
//# sourceMappingURL=LinkFilePickerTab.module.scss.js.map