/* tslint:disable */
require("./WebSearchTab.module.css");
var styles = {
    filePicker: 'filePicker_a5a77e5d',
    tabsContainer: 'tabsContainer_a5a77e5d',
    tabContainer: 'tabContainer_a5a77e5d',
    nav: 'nav_a5a77e5d',
    tabHeaderContainer: 'tabHeaderContainer_a5a77e5d',
    breadcrumbNav: 'breadcrumbNav_a5a77e5d',
    breadcrumbNavItem: 'breadcrumbNavItem_a5a77e5d',
    tab: 'tab_a5a77e5d',
    tabOffset: 'tabOffset_a5a77e5d',
    tabFiles: 'tabFiles_a5a77e5d',
    scrollablePaneWrapper: 'scrollablePaneWrapper_a5a77e5d',
    actionButtonsContainer: 'actionButtonsContainer_a5a77e5d',
    actionButtons: 'actionButtons_a5a77e5d',
    actionButton: 'actionButton_a5a77e5d',
    tabHeader: 'tabHeader_a5a77e5d',
    selectedTab: 'selectedTab_a5a77e5d',
    header: 'header_a5a77e5d',
    xlg: 'xlg_a5a77e5d',
    xxlg: 'xxlg_a5a77e5d',
    xxxlg: 'xxxlg_a5a77e5d',
    xxxxlg: 'xxxxlg_a5a77e5d',
    itemPickerTopBar: 'itemPickerTopBar_a5a77e5d',
    commandBarNoChevron: 'commandBarNoChevron_a5a77e5d',
    fileItem: 'fileItem_a5a77e5d',
    folderItem: 'folderItem_a5a77e5d',
    fileTypeIcon: 'fileTypeIcon_a5a77e5d',
    fileTypeIconIcon: 'fileTypeIconIcon_a5a77e5d',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_a5a77e5d',
    iconColumnHeader: 'iconColumnHeader_a5a77e5d',
    fileRow: 'fileRow_a5a77e5d',
    folderRow: 'folderRow_a5a77e5d',
    emptyFolder: 'emptyFolder_a5a77e5d',
    emptyFolderImage: 'emptyFolderImage_a5a77e5d',
    emptyFolderImageTag: 'emptyFolderImageTag_a5a77e5d',
    emptyFolderTitle: 'emptyFolderTitle_a5a77e5d',
    emptyFolderSubText: 'emptyFolderSubText_a5a77e5d',
    emptyFolderMobile: 'emptyFolderMobile_a5a77e5d',
    emptyFolderPc: 'emptyFolderPc_a5a77e5d',
    emptyFolderIcon: 'emptyFolderIcon_a5a77e5d',
    searchBoxContainer: 'searchBoxContainer_a5a77e5d',
    searchBoxMedium: 'searchBoxMedium_a5a77e5d',
    searchBox: 'searchBox_a5a77e5d',
    dropdownContainer: 'dropdownContainer_a5a77e5d',
    filterDropdown: 'filterDropdown_a5a77e5d',
    filePickerFolderCardGrid: 'filePickerFolderCardGrid_a5a77e5d',
    filePickerFolderCardTile: 'filePickerFolderCardTile_a5a77e5d',
    filePickerFolderCardPadder: 'filePickerFolderCardPadder_a5a77e5d',
    filePickerFolderCardSizer: 'filePickerFolderCardSizer_a5a77e5d',
    filePickerFolderCardImage: 'filePickerFolderCardImage_a5a77e5d',
    filePickerFolderCardLabel: 'filePickerFolderCardLabel_a5a77e5d',
    bingGridListCell: 'bingGridListCell_a5a77e5d',
    bingTile: 'bingTile_a5a77e5d',
    bingTileContent: 'bingTileContent_a5a77e5d',
    bingTileFrame: 'bingTileFrame_a5a77e5d',
    bingTileCheckCircle: 'bingTileCheckCircle_a5a77e5d',
    bingTileNamePlate: 'bingTileNamePlate_a5a77e5d',
    isSelected: 'isSelected_a5a77e5d',
    copyrightLabel: 'copyrightLabel_a5a77e5d',
    noResultLabel: 'noResultLabel_a5a77e5d',
    bingTileThumbnail: 'bingTileThumbnail_a5a77e5d',
    bingGrildList: 'bingGrildList_a5a77e5d'
};
export default styles;
/* tslint:enable */ 
//# sourceMappingURL=WebSearchTab.module.scss.js.map