/* tslint:disable */
require("./SiteFilePickerTab.module.css");
var styles = {
    filePicker: 'filePicker_cfebc66c',
    tabsContainer: 'tabsContainer_cfebc66c',
    tabContainer: 'tabContainer_cfebc66c',
    nav: 'nav_cfebc66c',
    tabHeaderContainer: 'tabHeaderContainer_cfebc66c',
    breadcrumbNav: 'breadcrumbNav_cfebc66c',
    breadcrumbNavItem: 'breadcrumbNavItem_cfebc66c',
    tab: 'tab_cfebc66c',
    tabOffset: 'tabOffset_cfebc66c',
    tabFiles: 'tabFiles_cfebc66c',
    scrollablePaneWrapper: 'scrollablePaneWrapper_cfebc66c',
    actionButtonsContainer: 'actionButtonsContainer_cfebc66c',
    actionButtons: 'actionButtons_cfebc66c',
    actionButton: 'actionButton_cfebc66c',
    tabHeader: 'tabHeader_cfebc66c',
    selectedTab: 'selectedTab_cfebc66c',
    header: 'header_cfebc66c',
    xlg: 'xlg_cfebc66c',
    xxlg: 'xxlg_cfebc66c',
    xxxlg: 'xxxlg_cfebc66c',
    xxxxlg: 'xxxxlg_cfebc66c',
    itemPickerTopBar: 'itemPickerTopBar_cfebc66c',
    commandBarNoChevron: 'commandBarNoChevron_cfebc66c',
    fileItem: 'fileItem_cfebc66c',
    folderItem: 'folderItem_cfebc66c',
    fileTypeIcon: 'fileTypeIcon_cfebc66c',
    fileTypeIconIcon: 'fileTypeIconIcon_cfebc66c',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_cfebc66c',
    iconColumnHeader: 'iconColumnHeader_cfebc66c',
    fileRow: 'fileRow_cfebc66c',
    folderRow: 'folderRow_cfebc66c',
    emptyFolder: 'emptyFolder_cfebc66c',
    emptyFolderImage: 'emptyFolderImage_cfebc66c',
    emptyFolderImageTag: 'emptyFolderImageTag_cfebc66c',
    emptyFolderTitle: 'emptyFolderTitle_cfebc66c',
    emptyFolderSubText: 'emptyFolderSubText_cfebc66c',
    emptyFolderMobile: 'emptyFolderMobile_cfebc66c',
    emptyFolderPc: 'emptyFolderPc_cfebc66c',
    emptyFolderIcon: 'emptyFolderIcon_cfebc66c'
};
export default styles;
/* tslint:enable */ 
//# sourceMappingURL=SiteFilePickerTab.module.scss.js.map